### ISSUE TITLE
Slow mouse response

### ISSUE THREAD

**Issue by glennfor** [JosiasAurel/chess-game#13]

**Comment by JosiasAurel** [comment]
Can you provide a description of this issue? Going to build and try anyway

**Comment by glennfor** [comment]
forgive my poor wording. I actually wrote an explanation of what was going on but somehow when I raised the issue it was removed. I think I must have messed sthg there

**Comment by glennfor** [comment]
The issue is I wrote some code in the gameloop to detect a mouse click and highlight the cell. The response was very sluggish so I was suspecting that drawing the sprites could be taking time... because it involves copying the sprite and then resizing it and converting to a texture before rendering. 

I guess we could see how to factor those steps out of the loop and have the ready-made textures available for rendering before the game loop starts
